### ISSUE TITLE
`rational` / `double` consumes dot if not followed by a number

### ISSUE THREAD

**Issue by kim** [haskell/attoparsec#112]
The documentation of states:

> [...] a trailing '.' or 'e' not followed by a number is not consumed.

and gives the examples: 

> rational "3.foo" == Done 3.0 ".foo"
> rational "3e"    == Done 3.0 "e"

I can verify this using attoparsec < 0.11.1.0, but later versions yield:

``` haskell
λ: :set -XOverloadedStrings
λ: import Data.Attoparsec.ByteString.Char8
λ: feed (parse rational "3.foo") mempty
Done "foo" 3.0
λ: feed (parse rational "3e") mempty
Done "e" 3.0
```

(Same results with `Data.Attoparsec.Text(.Lazy)`)

Since this has gone unnoticed since two major releases, I assume that most people didn't rely on it, so a simple documentation fix would resolve the issue. I am, however, aware of the [thyme](https://github.com/liyang/thyme) package's leap second table parser being broken because of this (will raise an issue there).

**Comment by geraldus** [comment]
By the way, there `rational` used in all examples of `double` parser documentation, should it be `double` instead (see https://github.com/bos/attoparsec/blob/master/Data/Attoparsec/ByteString/Char8.hs#L502-L515)?  I can open a new issue for this if needed.
