### ISSUE TITLE
Does attoparsec have a working CI setup?

### ISSUE THREAD

**Issue by vaibhavsagar** [haskell/attoparsec#163]
I see that there is a `.travis.yml` but as of this writing it doesn't look like it's actually enabled: https://travis-ci.org/bos/attoparsec.

**Comment by andreasabel** [comment]
Here is the CI now: https://github.com/haskell/attoparsec/blob/2472123ff91395f6d1835a5cf6a859d5c44bff04/.github/workflows/haskell-ci.yml

**Comment by vaibhavsagar** [comment]
Thank you!
