### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by phadej** [haskell/attoparsec#174]
(with bytestring-0.11 support)

cc @Bodigrim

**Comment by phadej** [comment]
Can a release with this patch be made, ping @bgamari.

(I get numerous requests to support bytestring-0.11 and most of them are blocked on attoparsec).

**Comment by bgamari** [comment]
Sure. Thanks for the ping.

**Comment by bgamari** [comment]
Released 0.13.2.5.

/close

**Comment by andreasabel** [comment]
It is a bit weird that the latest release 0.13.2.5 does not build with the latest GHC, 9.0.1.  Maybe an oversight? 
See https://github.com/bgamari/attoparsec/pull/6
