### ISSUE TITLE
Who maintains attoparsec?

### ISSUE THREAD

**Issue by chris-martin** [haskell/attoparsec#208]
- The readme says: Bryan O'Sullivan.
- The cabal file says: Bryan O'Sullivan and Ben Gamari.

Is it both, one or the other, or also including anyone else? Will submit a PR to fix the docs if anyone can give an answer.

Perhaps the note in the readme should simply be removed, since it can be at best redundant to and at worst conflicting with the cabal file.

**Comment by Bodigrim** [comment]
It's Ben.

**Comment by chris-martin** [comment]
Thanks!

**Comment by bgamari** [comment]
Indeed, thanks for the PR!

**Comment by askeblad** [comment]
merge #202

if merged #204

README.markdown → README.md

thereafter submit a new PR for removing bos from the newly named README.md

#203 is gratuitous

**Comment by askeblad** [comment]
@chris-martin some merges occurred today
